# Generated by Django 5.2.17 on 2026-08-19 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField()),
                ('server_entity_type', models.CharField(default='sale', max_length=50)),
                ('server_entity_id', models.BigIntegerField()),
                ('status', models.CharField(default='synced', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_transactions', to='accounts.device')),
            ],
            options={
                'indexes': [models.Index(fields=['server_entity_type', 'server_entity_id'], name='sync_synctr_server__f12ea4_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'client_uuid'), name='uniq_sync_device_client_uuid')],
            },
        ),
    ]
