"""Placeholder dashboard figures until sales, inventory, and courts ship."""


def dashboard_demo() -> dict:
    return {
        "kpis": [
            {
                "key": "total",
                "label": "Total Sales",
                "period": "Today",
                "value": "₱ 45,320.00",
                "delta": "+12.5%",
                "delta_label": "vs yesterday",
                "tone": "green",
                "sparkline": [18, 22, 20, 28, 26, 32, 38, 36, 42, 48],
            },
            {
                "key": "canteen",
                "label": "Canteen Sales",
                "period": "Today",
                "value": "₱ 28,260.00",
                "delta": "+8.3%",
                "delta_label": "vs yesterday",
                "tone": "blue",
                "sparkline": [12, 16, 14, 18, 22, 20, 24, 28, 26, 30],
            },
            {
                "key": "court",
                "label": "Court Revenue",
                "period": "Today",
                "value": "₱ 17,060.00",
                "delta": "+18.7%",
                "delta_label": "vs yesterday",
                "tone": "purple",
                "sparkline": [8, 10, 9, 14, 12, 16, 18, 17, 22, 24],
            },
            {
                "key": "transactions",
                "label": "Transactions",
                "period": "Today",
                "value": "128",
                "delta": "+15.2%",
                "delta_label": "vs yesterday",
                "tone": "orange",
                "sparkline": [20, 24, 22, 30, 28, 34, 32, 38, 40, 44],
            },
            {
                "key": "profit",
                "label": "Gross Profit",
                "period": "Today",
                "value": "₱ 19,450.00",
                "delta": "+11.1%",
                "delta_label": "vs yesterday",
                "tone": "teal",
                "sparkline": [14, 16, 15, 18, 20, 19, 22, 24, 23, 28],
            },
        ],
        "sales_overview": {
            "labels": ["May 18", "May 19", "May 20", "May 21", "May 22", "May 23", "May 24"],
            "total": [32000, 28000, 41000, 36000, 39000, 47000, 45320],
            "canteen": [21000, 18000, 25000, 22000, 24000, 30000, 28260],
            "court": [11000, 10000, 16000, 14000, 15000, 17000, 17060],
        },
        "payments": {
            "total": "₱ 45,320.00",
            "slices": [
                {"label": "Cash", "value": 33.7, "amount": "₱ 15,280", "color": "#16a34a"},
                {"label": "GCash", "value": 32.7, "amount": "₱ 14,820", "color": "#2563eb"},
                {"label": "Card", "value": 18.4, "amount": "₱ 8,340", "color": "#f59e0b"},
                {"label": "Maya", "value": 10.8, "amount": "₱ 4,890", "color": "#06b6d4"},
                {"label": "Other", "value": 2.2, "amount": "₱ 990", "color": "#94a3b8"},
            ],
        },
        "occupancy": {
            "percent": 62,
            "slices": [
                {"label": "Occupied", "value": 62, "detail": "16.5 hrs", "color": "#16a34a"},
                {"label": "Booked", "value": 18, "detail": "4.8 hrs", "color": "#3b82f6"},
                {"label": "Available", "value": 20, "detail": "5.3 hrs", "color": "#e2e8f0"},
            ],
        },
        "transactions": [
            {
                "id": "#TRX-0524-128",
                "type": "Canteen",
                "kind": "canteen",
                "amount": "₱ 450.00",
                "time": "2 min ago",
            },
            {
                "id": "#TRX-0524-127",
                "type": "Court Booking",
                "kind": "court",
                "amount": "₱ 800.00",
                "time": "8 min ago",
            },
            {
                "id": "#TRX-0524-126",
                "type": "Canteen",
                "kind": "canteen",
                "amount": "₱ 185.00",
                "time": "15 min ago",
            },
            {
                "id": "#TRX-0524-125",
                "type": "Canteen",
                "kind": "canteen",
                "amount": "₱ 320.00",
                "time": "22 min ago",
            },
            {
                "id": "#TRX-0524-124",
                "type": "Court Booking",
                "kind": "court",
                "amount": "₱ 1,200.00",
                "time": "35 min ago",
            },
            {
                "id": "#TRX-0524-123",
                "type": "Canteen",
                "kind": "canteen",
                "amount": "₱ 95.00",
                "time": "48 min ago",
            },
        ],
        "low_stock": [
            {"name": "Pickleball Ball (Outdoor)", "sku": "BALL-OUT-YLW", "qty": 12, "min": 24, "tone": "ball"},
            {"name": "Sports Drink 500ml", "sku": "BEV-SD-500", "qty": 8, "min": 20, "tone": "drink"},
            {"name": "Energy Bar", "sku": "SNK-BAR-01", "qty": 5, "min": 15, "tone": "bar"},
            {"name": "Grip Tape", "sku": "ACC-GRIP-BK", "qty": 3, "min": 10, "tone": "tape"},
        ],
        "shifts": [
            {"name": "Maria Santos", "initials": "MS", "open_time": "8:00 AM", "opening_cash": "₱ 5,000.00"},
            {"name": "Juan Dela Cruz", "initials": "JD", "open_time": "8:00 AM", "opening_cash": "₱ 5,000.00"},
            {"name": "Ana Reyes", "initials": "AR", "open_time": "2:00 PM", "opening_cash": "₱ 5,000.00"},
        ],
        "bookings": [
            {"slot": "11:00 AM – 12:00 PM", "court": "Court 1", "customer": "Roberto Cruz"},
            {"slot": "11:00 AM – 1:00 PM", "court": "Court 3", "customer": "Miguel Santos"},
            {"slot": "12:00 PM – 2:00 PM", "court": "Court 2", "customer": "Lisa Tan"},
            {"slot": "1:00 PM – 2:00 PM", "court": "Court 4", "customer": "Pedro Garcia"},
            {"slot": "2:00 PM – 4:00 PM", "court": "Court 1", "customer": "Sofia Reyes"},
        ],
        "financial": [
            {"label": "Total Sales", "value": "₱ 1,248,650.00", "tone": "blue"},
            {"label": "Total Expenses", "value": "₱ 186,420.00", "tone": "red"},
            {"label": "Gross Profit", "value": "₱ 542,180.00", "tone": "green"},
            {"label": "Net Profit", "value": "₱ 355,760.00", "tone": "purple"},
        ],
        "notification_count": 3,
        "is_demo": True,
    }
