# Generated by Django 5.2.17 on 2026-08-18 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('branches', '0001_initial'),
        ('products', '0002_branchproductprice'),
        ('sales', '0001_initial'),
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='shifts.cashiershift'),
        ),
        migrations.AddField(
            model_name='refunditem',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.refund'),
        ),
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='accounts.device'),
        ),
        migrations.AddField(
            model_name='sale',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='shifts.cashiershift'),
        ),
        migrations.AddField(
            model_name='refund',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='heldorder',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hold', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='refunditem',
            name='sale_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_items', to='sales.saleitem'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['branch', 'created_at'], name='sales_sale_branch__7662c5_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['shift', 'status'], name='sales_sale_shift_i_58cbd7_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('branch', 'transaction_number'), name='uniq_sale_txn_branch'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('receipt_number', ''), _negated=True), fields=('branch', 'receipt_number'), name='uniq_sale_receipt_branch'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(fields=('branch', 'refund_number'), name='uniq_refund_branch_number'),
        ),
    ]
