# Generated by Django 5.2.17 on 2026-08-19 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='branches.branch')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['branch', 'is_active'], name='customers_c_branch__e67b0c_idx'), models.Index(fields=['name'], name='customers_c_name_f018e2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('mobile', ''), _negated=True), fields=('branch', 'mobile'), name='uniq_customer_branch_mobile')],
            },
        ),
    ]
