# Generated by Django 5.2.17 on 2026-08-22 04:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1200'), max_digits=5),
        ),
        migrations.AddField(
            model_name='branch',
            name='vat_registered',
            field=models.BooleanField(default=True),
        ),
    ]
